#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# fakeroute-plot
#
# fakeroute-plot plots the topologies simulated by fakeroute using 'dot'.
#
# Author: Jordan Augé <jordan.auge@lip6.fr>
# Copyright (C)2011, UPMC Sorbonnes Universités / LIP6
#
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
# 
# You should have received a copy of the GNU General Public License along with
# this program; see the file COPYING.  If not, write to the Free Software
# Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
import sys, os, re
import pydot

CONFIGPATH=['./targets', '~/.fakeroute/targets', '/etc/fakeroute/targets']

def get_cfgpath():
    for path in CONFIGPATH:
        if os.path.exists(path):
            return path
    return None

def sort_ip_list(l):
    ll = [tuple(x.split('.')) for x in l]
    ll.sort()
    return ['.'.join(x) for x in ll]

def get_handled_files(cfgpath):
    handled = {}
    dirList=os.listdir(cfgpath)
    for fname in dirList:
        if re.match('[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-.*)?', fname):
            handled[fname.split('-')[0]] = fname
    return handled

def main(ip):
    cfgpath = get_cfgpath()
    handled = get_handled_files(cfgpath)

    fn = '%s/%s' % (get_cfgpath(), handled[ip])
    graph = pydot.Dot(graph_type='digraph')

    lines = [x.strip() for x in open(fn, 'r').readlines()]
    for l in lines:
        if not l or l[0] == '#':
            continue
        l = l.split()
        edge = pydot.Edge(l[0], l[1])
        graph.add_edge(edge)

    print "I: Wrote file %s.png" % ip
    graph.write_png('%s.png' % ip)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print "Usage: fakeroute-plot.py IP_ADDRESS"
        sys.exit(-1)
    ip = sys.argv[1]
    main(ip)
